trigger:
- main   # Rama que dispara la pipeline

pool:
  vmImage: 'ubuntu-latest'   # Agente hospedado en Azure

steps:
# --- Paso 1: Checkout del repositorio principal ---
- checkout: self
  fetchDepth: 1    # Trae solo el último commit (más rápido)

# --- Paso 2: Checkout de otro repositorio externo ---
- checkout: git://MyProject/OtherRepo
  persistCredentials: true   # Mantener credenciales si luego haces push
  clean: true                # Limpia antes de hacer checkout

# --- Paso 3: Restaurar dependencias Maven ---
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true

# --- Paso 4: Ejecutar pruebas ---
- script: |
    echo "Ejecutando pruebas unitarias..."
    mvn test
  displayName: "Pruebas con Maven"

# --- Paso 5: Publicar artefacto ---
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target'
    artifactName: 'drop'
    publishLocation: 'Container'
